//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50522.1
// 
namespace SalesInformation.MyRef {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductMaster", Namespace="http://schemas.datacontract.org/2004/07/WCF_Sales_Service", IsReference=true)]
    public partial class ProductMaster : SalesInformation.MyRef.EntityObject {
        
        private int ProductIDField;
        
        private string ProductNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.RowOrderMaster> RowOrderMastersField;
        
        private int UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.RowOrderMaster> RowOrderMasters {
            get {
                return this.RowOrderMastersField;
            }
            set {
                if ((object.ReferenceEquals(this.RowOrderMastersField, value) != true)) {
                    this.RowOrderMastersField = value;
                    this.RaisePropertyChanged("RowOrderMasters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.RowOrderMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.DealerMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.BillMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.ProductMaster))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.RowOrderMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.DealerMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.BillMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.ProductMaster))]
    public partial class EntityObject : SalesInformation.MyRef.StructuralObject {
        
        private SalesInformation.MyRef.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesInformation.MyRef.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RowOrderMaster", Namespace="http://schemas.datacontract.org/2004/07/WCF_Sales_Service", IsReference=true)]
    public partial class RowOrderMaster : SalesInformation.MyRef.EntityObject {
        
        private int DealerIDField;
        
        private SalesInformation.MyRef.DealerMaster DealerMasterField;
        
        private SalesInformation.MyRef.EntityReferenceOfDealerMastersCCKwiqE DealerMasterReferenceField;
        
        private int OrderIDField;
        
        private int OrderPriceField;
        
        private int ProductIDField;
        
        private SalesInformation.MyRef.ProductMaster ProductMasterField;
        
        private SalesInformation.MyRef.EntityReferenceOfProductMastersCCKwiqE ProductMasterReferenceField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealerID {
            get {
                return this.DealerIDField;
            }
            set {
                if ((this.DealerIDField.Equals(value) != true)) {
                    this.DealerIDField = value;
                    this.RaisePropertyChanged("DealerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesInformation.MyRef.DealerMaster DealerMaster {
            get {
                return this.DealerMasterField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerMasterField, value) != true)) {
                    this.DealerMasterField = value;
                    this.RaisePropertyChanged("DealerMaster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesInformation.MyRef.EntityReferenceOfDealerMastersCCKwiqE DealerMasterReference {
            get {
                return this.DealerMasterReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerMasterReferenceField, value) != true)) {
                    this.DealerMasterReferenceField = value;
                    this.RaisePropertyChanged("DealerMasterReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderPrice {
            get {
                return this.OrderPriceField;
            }
            set {
                if ((this.OrderPriceField.Equals(value) != true)) {
                    this.OrderPriceField = value;
                    this.RaisePropertyChanged("OrderPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesInformation.MyRef.ProductMaster ProductMaster {
            get {
                return this.ProductMasterField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductMasterField, value) != true)) {
                    this.ProductMasterField = value;
                    this.RaisePropertyChanged("ProductMaster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesInformation.MyRef.EntityReferenceOfProductMastersCCKwiqE ProductMasterReference {
            get {
                return this.ProductMasterReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductMasterReferenceField, value) != true)) {
                    this.ProductMasterReferenceField = value;
                    this.RaisePropertyChanged("ProductMasterReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealerMaster", Namespace="http://schemas.datacontract.org/2004/07/WCF_Sales_Service", IsReference=true)]
    public partial class DealerMaster : SalesInformation.MyRef.EntityObject {
        
        private System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.BillMaster> BillMastersField;
        
        private int DealerIDField;
        
        private string DealerNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.RowOrderMaster> RowOrderMastersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.BillMaster> BillMasters {
            get {
                return this.BillMastersField;
            }
            set {
                if ((object.ReferenceEquals(this.BillMastersField, value) != true)) {
                    this.BillMastersField = value;
                    this.RaisePropertyChanged("BillMasters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealerID {
            get {
                return this.DealerIDField;
            }
            set {
                if ((this.DealerIDField.Equals(value) != true)) {
                    this.DealerIDField = value;
                    this.RaisePropertyChanged("DealerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerName {
            get {
                return this.DealerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerNameField, value) != true)) {
                    this.DealerNameField = value;
                    this.RaisePropertyChanged("DealerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.RowOrderMaster> RowOrderMasters {
            get {
                return this.RowOrderMastersField;
            }
            set {
                if ((object.ReferenceEquals(this.RowOrderMastersField, value) != true)) {
                    this.RowOrderMastersField = value;
                    this.RaisePropertyChanged("RowOrderMasters");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillMaster", Namespace="http://schemas.datacontract.org/2004/07/WCF_Sales_Service", IsReference=true)]
    public partial class BillMaster : SalesInformation.MyRef.EntityObject {
        
        private int DealerIDField;
        
        private SalesInformation.MyRef.DealerMaster DealerMasterField;
        
        private SalesInformation.MyRef.EntityReferenceOfDealerMastersCCKwiqE DealerMasterReferenceField;
        
        private int InvoiceNoField;
        
        private int TotalBillField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealerID {
            get {
                return this.DealerIDField;
            }
            set {
                if ((this.DealerIDField.Equals(value) != true)) {
                    this.DealerIDField = value;
                    this.RaisePropertyChanged("DealerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesInformation.MyRef.DealerMaster DealerMaster {
            get {
                return this.DealerMasterField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerMasterField, value) != true)) {
                    this.DealerMasterField = value;
                    this.RaisePropertyChanged("DealerMaster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesInformation.MyRef.EntityReferenceOfDealerMastersCCKwiqE DealerMasterReference {
            get {
                return this.DealerMasterReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerMasterReferenceField, value) != true)) {
                    this.DealerMasterReferenceField = value;
                    this.RaisePropertyChanged("DealerMasterReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceNo {
            get {
                return this.InvoiceNoField;
            }
            set {
                if ((this.InvoiceNoField.Equals(value) != true)) {
                    this.InvoiceNoField = value;
                    this.RaisePropertyChanged("InvoiceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalBill {
            get {
                return this.TotalBillField;
            }
            set {
                if ((this.TotalBillField.Equals(value) != true)) {
                    this.TotalBillField = value;
                    this.RaisePropertyChanged("TotalBill");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EntityContainerNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.EntityKeyMember> EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityReferenceOfDealerMastersCCKwiqE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityReferenceOfProductMastersCCKwiqE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.ProductMaster>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.RowOrderMaster>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.RowOrderMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.DealerMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.BillMaster>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.BillMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.DealerMaster>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.EntityKeyMember>))]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfDealerMastersCCKwiqE", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfDealerMastersCCKwiqE : SalesInformation.MyRef.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityReferenceOfProductMastersCCKwiqE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityReferenceOfDealerMastersCCKwiqE))]
    public partial class EntityReference : SalesInformation.MyRef.RelatedEnd {
        
        private SalesInformation.MyRef.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesInformation.MyRef.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityReferenceOfProductMastersCCKwiqE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesInformation.MyRef.EntityReferenceOfDealerMastersCCKwiqE))]
    public partial class RelatedEnd : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfProductMastersCCKwiqE", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfProductMastersCCKwiqE : SalesInformation.MyRef.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyRef.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProducts", ReplyAction="http://tempuri.org/IService/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.ProductMaster>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDealers", ReplyAction="http://tempuri.org/IService/GetDealersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.DealerMaster>> GetDealersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GenerateInvoice", ReplyAction="http://tempuri.org/IService/GenerateInvoiceResponse")]
        System.Threading.Tasks.Task<int> GenerateInvoiceAsync(SalesInformation.MyRef.BillMaster objBill, System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.RowOrderMaster> orders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetInvoices", ReplyAction="http://tempuri.org/IService/GetInvoicesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.BillMaster>> GetInvoicesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SalesInformation.MyRef.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SalesInformation.MyRef.IService>, SalesInformation.MyRef.IService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.ProductMaster>> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.DealerMaster>> GetDealersAsync() {
            return base.Channel.GetDealersAsync();
        }
        
        public System.Threading.Tasks.Task<int> GenerateInvoiceAsync(SalesInformation.MyRef.BillMaster objBill, System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.RowOrderMaster> orders) {
            return base.Channel.GenerateInvoiceAsync(objBill, orders);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SalesInformation.MyRef.BillMaster>> GetInvoicesAsync() {
            return base.Channel.GetInvoicesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8090/WCF_Sales-Service/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService,
        }
    }
}
