//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SalesInfoModel", "FK_BillMaster_DealerMaster", "DealerMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCF_Sales_Service.DealerMaster), "BillMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCF_Sales_Service.BillMaster), true)]
[assembly: EdmRelationshipAttribute("SalesInfoModel", "FK_RowOrderMaster_RowOrderMaster", "DealerMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCF_Sales_Service.DealerMaster), "RowOrderMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCF_Sales_Service.RowOrderMaster), true)]
[assembly: EdmRelationshipAttribute("SalesInfoModel", "FK_RowOrderMaster_ProductMaster", "ProductMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCF_Sales_Service.ProductMaster), "RowOrderMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCF_Sales_Service.RowOrderMaster), true)]

#endregion

namespace WCF_Sales_Service
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SalesInfoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SalesInfoEntities object using the connection string found in the 'SalesInfoEntities' section of the application configuration file.
        /// </summary>
        public SalesInfoEntities() : base("name=SalesInfoEntities", "SalesInfoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SalesInfoEntities object.
        /// </summary>
        public SalesInfoEntities(string connectionString) : base(connectionString, "SalesInfoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SalesInfoEntities object.
        /// </summary>
        public SalesInfoEntities(EntityConnection connection) : base(connection, "SalesInfoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BillMaster> BillMasters
        {
            get
            {
                if ((_BillMasters == null))
                {
                    _BillMasters = base.CreateObjectSet<BillMaster>("BillMasters");
                }
                return _BillMasters;
            }
        }
        private ObjectSet<BillMaster> _BillMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DealerMaster> DealerMasters
        {
            get
            {
                if ((_DealerMasters == null))
                {
                    _DealerMasters = base.CreateObjectSet<DealerMaster>("DealerMasters");
                }
                return _DealerMasters;
            }
        }
        private ObjectSet<DealerMaster> _DealerMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductMaster> ProductMasters
        {
            get
            {
                if ((_ProductMasters == null))
                {
                    _ProductMasters = base.CreateObjectSet<ProductMaster>("ProductMasters");
                }
                return _ProductMasters;
            }
        }
        private ObjectSet<ProductMaster> _ProductMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RowOrderMaster> RowOrderMasters
        {
            get
            {
                if ((_RowOrderMasters == null))
                {
                    _RowOrderMasters = base.CreateObjectSet<RowOrderMaster>("RowOrderMasters");
                }
                return _RowOrderMasters;
            }
        }
        private ObjectSet<RowOrderMaster> _RowOrderMasters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BillMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBillMasters(BillMaster billMaster)
        {
            base.AddObject("BillMasters", billMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DealerMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDealerMasters(DealerMaster dealerMaster)
        {
            base.AddObject("DealerMasters", dealerMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductMasters(ProductMaster productMaster)
        {
            base.AddObject("ProductMasters", productMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RowOrderMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRowOrderMasters(RowOrderMaster rowOrderMaster)
        {
            base.AddObject("RowOrderMasters", rowOrderMaster);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SalesInfoModel", Name="BillMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BillMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BillMaster object.
        /// </summary>
        /// <param name="invoiceNo">Initial value of the InvoiceNo property.</param>
        /// <param name="dealerID">Initial value of the DealerID property.</param>
        /// <param name="totalBill">Initial value of the TotalBill property.</param>
        public static BillMaster CreateBillMaster(global::System.Int32 invoiceNo, global::System.Int32 dealerID, global::System.Int32 totalBill)
        {
            BillMaster billMaster = new BillMaster();
            billMaster.InvoiceNo = invoiceNo;
            billMaster.DealerID = dealerID;
            billMaster.TotalBill = totalBill;
            return billMaster;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvoiceNo
        {
            get
            {
                return _InvoiceNo;
            }
            set
            {
                if (_InvoiceNo != value)
                {
                    OnInvoiceNoChanging(value);
                    ReportPropertyChanging("InvoiceNo");
                    _InvoiceNo = StructuralObject.SetValidValue(value, "InvoiceNo");
                    ReportPropertyChanged("InvoiceNo");
                    OnInvoiceNoChanged();
                }
            }
        }
        private global::System.Int32 _InvoiceNo;
        partial void OnInvoiceNoChanging(global::System.Int32 value);
        partial void OnInvoiceNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DealerID
        {
            get
            {
                return _DealerID;
            }
            set
            {
                OnDealerIDChanging(value);
                ReportPropertyChanging("DealerID");
                _DealerID = StructuralObject.SetValidValue(value, "DealerID");
                ReportPropertyChanged("DealerID");
                OnDealerIDChanged();
            }
        }
        private global::System.Int32 _DealerID;
        partial void OnDealerIDChanging(global::System.Int32 value);
        partial void OnDealerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalBill
        {
            get
            {
                return _TotalBill;
            }
            set
            {
                OnTotalBillChanging(value);
                ReportPropertyChanging("TotalBill");
                _TotalBill = StructuralObject.SetValidValue(value, "TotalBill");
                ReportPropertyChanged("TotalBill");
                OnTotalBillChanged();
            }
        }
        private global::System.Int32 _TotalBill;
        partial void OnTotalBillChanging(global::System.Int32 value);
        partial void OnTotalBillChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SalesInfoModel", "FK_BillMaster_DealerMaster", "DealerMaster")]
        public DealerMaster DealerMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DealerMaster>("SalesInfoModel.FK_BillMaster_DealerMaster", "DealerMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DealerMaster>("SalesInfoModel.FK_BillMaster_DealerMaster", "DealerMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DealerMaster> DealerMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DealerMaster>("SalesInfoModel.FK_BillMaster_DealerMaster", "DealerMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DealerMaster>("SalesInfoModel.FK_BillMaster_DealerMaster", "DealerMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SalesInfoModel", Name="DealerMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DealerMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DealerMaster object.
        /// </summary>
        /// <param name="dealerID">Initial value of the DealerID property.</param>
        /// <param name="dealerName">Initial value of the DealerName property.</param>
        public static DealerMaster CreateDealerMaster(global::System.Int32 dealerID, global::System.String dealerName)
        {
            DealerMaster dealerMaster = new DealerMaster();
            dealerMaster.DealerID = dealerID;
            dealerMaster.DealerName = dealerName;
            return dealerMaster;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DealerID
        {
            get
            {
                return _DealerID;
            }
            set
            {
                if (_DealerID != value)
                {
                    OnDealerIDChanging(value);
                    ReportPropertyChanging("DealerID");
                    _DealerID = StructuralObject.SetValidValue(value, "DealerID");
                    ReportPropertyChanged("DealerID");
                    OnDealerIDChanged();
                }
            }
        }
        private global::System.Int32 _DealerID;
        partial void OnDealerIDChanging(global::System.Int32 value);
        partial void OnDealerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DealerName
        {
            get
            {
                return _DealerName;
            }
            set
            {
                OnDealerNameChanging(value);
                ReportPropertyChanging("DealerName");
                _DealerName = StructuralObject.SetValidValue(value, false, "DealerName");
                ReportPropertyChanged("DealerName");
                OnDealerNameChanged();
            }
        }
        private global::System.String _DealerName;
        partial void OnDealerNameChanging(global::System.String value);
        partial void OnDealerNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SalesInfoModel", "FK_BillMaster_DealerMaster", "BillMaster")]
        public EntityCollection<BillMaster> BillMasters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BillMaster>("SalesInfoModel.FK_BillMaster_DealerMaster", "BillMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BillMaster>("SalesInfoModel.FK_BillMaster_DealerMaster", "BillMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SalesInfoModel", "FK_RowOrderMaster_RowOrderMaster", "RowOrderMaster")]
        public EntityCollection<RowOrderMaster> RowOrderMasters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RowOrderMaster>("SalesInfoModel.FK_RowOrderMaster_RowOrderMaster", "RowOrderMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RowOrderMaster>("SalesInfoModel.FK_RowOrderMaster_RowOrderMaster", "RowOrderMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SalesInfoModel", Name="ProductMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductMaster object.
        /// </summary>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="unitPrice">Initial value of the UnitPrice property.</param>
        public static ProductMaster CreateProductMaster(global::System.Int32 productID, global::System.String productName, global::System.Int32 unitPrice)
        {
            ProductMaster productMaster = new ProductMaster();
            productMaster.ProductID = productID;
            productMaster.ProductName = productName;
            productMaster.UnitPrice = unitPrice;
            return productMaster;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value, "ProductID");
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false, "ProductName");
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value, "UnitPrice");
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private global::System.Int32 _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Int32 value);
        partial void OnUnitPriceChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SalesInfoModel", "FK_RowOrderMaster_ProductMaster", "RowOrderMaster")]
        public EntityCollection<RowOrderMaster> RowOrderMasters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RowOrderMaster>("SalesInfoModel.FK_RowOrderMaster_ProductMaster", "RowOrderMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RowOrderMaster>("SalesInfoModel.FK_RowOrderMaster_ProductMaster", "RowOrderMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SalesInfoModel", Name="RowOrderMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RowOrderMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RowOrderMaster object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="dealerID">Initial value of the DealerID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="orderPrice">Initial value of the OrderPrice property.</param>
        public static RowOrderMaster CreateRowOrderMaster(global::System.Int32 orderID, global::System.Int32 dealerID, global::System.Int32 productID, global::System.Int32 quantity, global::System.Int32 orderPrice)
        {
            RowOrderMaster rowOrderMaster = new RowOrderMaster();
            rowOrderMaster.OrderID = orderID;
            rowOrderMaster.DealerID = dealerID;
            rowOrderMaster.ProductID = productID;
            rowOrderMaster.Quantity = quantity;
            rowOrderMaster.OrderPrice = orderPrice;
            return rowOrderMaster;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value, "OrderID");
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DealerID
        {
            get
            {
                return _DealerID;
            }
            set
            {
                OnDealerIDChanging(value);
                ReportPropertyChanging("DealerID");
                _DealerID = StructuralObject.SetValidValue(value, "DealerID");
                ReportPropertyChanged("DealerID");
                OnDealerIDChanged();
            }
        }
        private global::System.Int32 _DealerID;
        partial void OnDealerIDChanging(global::System.Int32 value);
        partial void OnDealerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value, "ProductID");
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value, "Quantity");
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Int32 _Quantity;
        partial void OnQuantityChanging(global::System.Int32 value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderPrice
        {
            get
            {
                return _OrderPrice;
            }
            set
            {
                OnOrderPriceChanging(value);
                ReportPropertyChanging("OrderPrice");
                _OrderPrice = StructuralObject.SetValidValue(value, "OrderPrice");
                ReportPropertyChanged("OrderPrice");
                OnOrderPriceChanged();
            }
        }
        private global::System.Int32 _OrderPrice;
        partial void OnOrderPriceChanging(global::System.Int32 value);
        partial void OnOrderPriceChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SalesInfoModel", "FK_RowOrderMaster_RowOrderMaster", "DealerMaster")]
        public DealerMaster DealerMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DealerMaster>("SalesInfoModel.FK_RowOrderMaster_RowOrderMaster", "DealerMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DealerMaster>("SalesInfoModel.FK_RowOrderMaster_RowOrderMaster", "DealerMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DealerMaster> DealerMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DealerMaster>("SalesInfoModel.FK_RowOrderMaster_RowOrderMaster", "DealerMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DealerMaster>("SalesInfoModel.FK_RowOrderMaster_RowOrderMaster", "DealerMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SalesInfoModel", "FK_RowOrderMaster_ProductMaster", "ProductMaster")]
        public ProductMaster ProductMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductMaster>("SalesInfoModel.FK_RowOrderMaster_ProductMaster", "ProductMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductMaster>("SalesInfoModel.FK_RowOrderMaster_ProductMaster", "ProductMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProductMaster> ProductMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductMaster>("SalesInfoModel.FK_RowOrderMaster_ProductMaster", "ProductMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProductMaster>("SalesInfoModel.FK_RowOrderMaster_ProductMaster", "ProductMaster", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
